const phrases = {
    1: "Our work group at the school in Tanzania is incredibly dedicated, always striving to make a positive impact on our community.",
    2: "Every member of our work group brings unique skills and perspectives, making our team diverse and dynamic.",
    3: "Collaboration within our school group in Tanzania fosters creativity and innovative solutions to challenges.",
    4: "The support and encouragement we offer each other in our work group help us grow both personally and professionally.",
    5: "Our teamwork has led to remarkable progress in our school projects, benefiting everyone involved.",
    6: "We take pride in our commitment to improving educational outcomes for all students in Tanzania.",
    7: "Our work group is a shining example of unity and shared purpose in the pursuit of academic excellence.",
    8: "We celebrate each achievement together, knowing that every success is a result of collective effort.",
    9: "The positive energy in our work group makes every task enjoyable and rewarding.",
    10: "We learn from each other every day, which strengthens our skills and knowledge.",
    11: "Our group meetings are filled with constructive discussions and innovative ideas.",
    12: "We respect and value each member’s contributions, fostering a sense of belonging and purpose.",
    13: "Our collaborative spirit is the foundation of our success in various school initiatives.",
    14: "The friendships we’ve formed in our work group make our school experience even more enriching.",
    15: "We are committed to making a lasting difference in our school and community through our projects.",
    16: "Our group’s enthusiasm for learning and growth is truly contagious.",
    17: "We are proud of the positive impact our teamwork has on the school environment.",
    18: "Every challenge we face is an opportunity for us to grow stronger as a team.",
    19: "Our shared goals inspire us to work diligently and passionately.",
    20: "We support each other in overcoming obstacles, celebrating each victory together.",
    21: "Our work group exemplifies the power of collaboration and mutual respect.",
    22: "We are dedicated to fostering a culture of excellence and continuous improvement.",
    23: "The synergy in our group drives us to achieve remarkable results.",
    24: "We are united by a common vision to enhance educational experiences in Tanzania.",
    25: "Our commitment to each other and our goals is unwavering and inspiring.",
    26: "We cherish the learning experiences we share in our work group.",
    27: "Our group’s positive attitude and resilience make us unstoppable.",
    28: "We are grateful for the opportunity to work together and make a difference.",
    29: "Our teamwork is a testament to what can be achieved through cooperation and dedication.",
    30: "We look forward to each project, knowing we will accomplish great things together."
};

module.exports = { phrases };